accounts/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
]

blogs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.BlogListView.as_view(), name='home'),
path('post/<int:pk>/', views.BlogDetailView.as_view(), name='post_detail'),
]

forum/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.BlogListView.as_view(), name='forum'),
path('post/<int:pk>/', views.BlogDetailView.as_view(), name='forum_detail'),
path('post/new/', views.BlogCreateView.as_view(), name='post_new'),
]

woc7012grp/urls.py
from django.contrib import admin
from django.urls import path
from django.views.generic.base import TemplateView
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.conf.urls import include
urlpatterns = [
    path('admin/', admin.site.urls),

    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('blogs/', include('blogs.urls')),
path('forum/', include('forum.urls')),

]

accounts/models.py
from django.db import models

# Create your models here.

blogs/models.py
from django.db import models

from django.db import models


class Post(models.Model):
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    title = models.CharField(max_length=200)
    text = models.TextField()
    post_logo = models.CharField(max_length=200)

    def __str__(self):
        return self.title

forum/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.urls import reverse



class Forum_post(models.Model):
    author = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
    )
    title = models.CharField(max_length=200)
    text = models.TextField()

    def get_absolute_url(self):
        return reverse('forum')

    def __str__(self):
        return self.title

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

blogs/views.py
from django.http import  HttpResponseForbidden
from django.views.generic import ListView, DetailView

from . models import Post


class BlogListView(ListView):
    model = Post
    template_name = 'blog.html'




class BlogDetailView(DetailView):
    model = Post
    template_name = 'blog_post_detail.html'
    context_object_name = 'catalogue_detail'

forum/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
from .models import Forum_post


class BlogListView(ListView):
    model = Forum_post
    template_name = 'forum.html'

class BlogDetailView(DetailView):
    model = Forum_post
    template_name = 'forum_detail.html'
    context_object_name = 'post_forum'

class BlogCreateView(CreateView):
    model = Forum_post
    #model.author = User.username
    template_name = 'post_new.html'
    fields = '__all__'
    #fields = ['title', 'text']

templates/base.html
{% if user.is_authenticated %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Football community</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/navbar-top/navbar-top.css" rel="stylesheet">

    {% block stylesheet %}

{% endblock stylesheet %}
</head>

<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="#">{% if user.is_authenticated %}
  Hi {{ user.username }}{% endif %} Welcome</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'forum' %}">Forum</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
        </ul>
    </div>
</nav>

<main role="main" class="container">

        {% block content %}
        {% endblock %}

</main>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="../../../../assets/js/vendor/popper.min.js"></script>
<script src="../../../../dist/js/bootstrap.min.js"></script>
</body>
</html>
{% else %}
    <p>You are not logged in.</p>
    <h1>Access Denied</h1>
    <span>We're sorry, but you are not authorized to view this page (Error: 403)</span>
    <a href="{% url 'login' %}">login</a>
{% endif %}

templates/blog.html
{% extends 'base.html' %}


{% block stylesheet %}
    <link href="https://getbootstrap.com/docs/4.0/examples/album/album.css" rel="stylesheet">

{% endblock stylesheet %}



{% block content %}
    <body>


    <main role="main">

        <section class="jumbotron text-center">
            <div class="container">
                <h1 class="jumbotron-heading">Latest news</h1>
                <p class="lead text-muted">here are the latest catalogue of news</p>
            </div>
        </section>

        <div class="album text-muted">
            <div class="container">

                <div class="row">

                    {% for post in object_list %}
                        <div class="card">
                            <div class="post-entry">
                                <a href="{% url 'post_detail' post.pk %}">
                                    <img border="0" alt="{{ post.title }}" src="{{ post.post_logo }}" width="350" height="250">
                                </a>
                                <p class="card-text">{{ post.text }}</p>

                            </div>
                        </div>
                    {% endfor %}

                </div>

            </div>
        </div>

    </main>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/assets/js/vendor/popper.min.js"></script>
    <script src="https://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <script src="https://getbootstrap.com/assets/js/vendor/holder.min.js"></script>
    <script>
        Holder.addTheme('thumb', {
            bg: '#55595c',
            fg: '#eceeef',
            text: 'Thumbnail'
        });
    </script>
    </body>

{% endblock content %}

templates/blog_post_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="post-entry">
    <h2>{{ catalogue_detail.title }}</h2>
    <p>{{ catalogue_detail.text }}</p>
  </div>

{% endblock content %}

templates/forum.html
{% extends 'base.html' %}


{% block stylesheet %}
    <!-- Bootstrap core CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-clean-blog/vendor/bootstrap/css/bootstrap.min.css"
          rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-clean-blog/vendor/font-awesome/css/font-awesome.min.css"
          rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet'
          type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800'
          rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-clean-blog/css/clean-blog.min.css" rel="stylesheet">

{% endblock stylesheet %}


{% block content %}

    <body>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">


                {% for post in object_list %}
                    <div class="post-entry">
                        <div class="post-preview">
                            <a href="{% url 'forum_detail' post.pk %}">
                                <h2 class="post-title">
                                    {{ post.title }}
                                </h2>
                                <h3 class="post-subtitle">
                                    {{ post.text }}
                                </h3>
                            </a>
                            <p class="post-meta">Posted by {{ post.author }}</p>
                        </div>
                        <hr>
                    </div>
                {% endfor %}
                <!-- Pager -->
                <div class="clearfix">
                    <a class="btn btn-primary float-right" href="{% url 'post_new' %}">News Post &rarr;</a>
                </div>
            </div>
        </div>
    </div>

    <hr>


    <!-- Bootstrap core JavaScript -->
    <script src="https://blackrockdigital.github.io/startbootstrap-clean-blog/vendor/jquery/jquery.min.js"></script>
    <script src="https://blackrockdigital.github.io/startbootstrap-clean-blog/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="https://blackrockdigital.github.io/startbootstrap-clean-blog/js/clean-blog.min.js"></script>

    </body>

{% endblock content %}

templates/forum_detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="post-entry">
    <h2>{{ post_forum.title }}</h2>
    <p>{{ post_forum.text }}</p>
  </div>

{% endblock content %}

templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Welcome</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/cover/cover.css" rel="stylesheet">




  </head>

  <body background="https://images.pexels.com/photos/39562/the-ball-stadion-football-the-pitch-39562.jpeg?w=940&h=650&dpr=2&auto=compress&cs=tinysrgb">

    <div class="site-wrapper" >

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <header class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">All about football</h3>
              <nav class="nav nav-masthead">
                <a class="nav-link active" href="#">Home</a>
                  {% if user.is_authenticated %}
                      <a class="nav-link active" href="{% url 'logout' %}">Logout</a>
                  {% endif %}
              </nav>
            </div>
          </header>

          <main role="main" class="inner cover">
            <h1 class="cover-heading">Welcome to our comunity</h1>
            <p class="lead">In our website you can find latest news about football and also discuss in the forum with other users.</p>
            <p class="lead">
              <a href="{% url 'login' %}" class="btn btn-lg btn-secondary">Get started</a>
            </p>
          </main>



        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://getbootstrap.com/assets/js/vendor/popper.min.js"></script>
    <script src="https://getbootstrap.com/dist/js/bootstrap.min.js"></script>
  </body>
</html>

templates/post_new.html
{% extends 'base.html' %}

{% block content %}
    <h1>New post</h1>
    <form action="" method="post">{% csrf_token %}
        <p><label for="id_author">Author:</label> <select name="author" required id="id_author">
  <option value="" selected>username</option>

  <option value="{{ user.id }}">{{ user.username }}</option>



</select></p>
<p><label for="id_title">Title:</label> <input type="text" name="title" maxlength="200" required id="id_title" /></p>
<p><label for="id_text">Text:</label> <textarea name="text" cols="40" rows="10" required id="id_text">
</textarea></p>
        <input type="submit" value="Save"/>
    </form>
{% endblock %}

templates/signup.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>Signup</title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/signin/signin.css" rel="stylesheet">


</head>

<body background="https://images.pexels.com/photos/39562/the-ball-stadion-football-the-pitch-39562.jpeg?w=940&h=650&dpr=2&auto=compress&cs=tinysrgb">

<div class="container">

    <form class="form-signin" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">Please sign up</h2>


        <p><label for="id_username" class="sr-only">Username:</label> <input type="text" name="username"
                                                                             class="form-control"
                                                                             placeholder="Username"
                                                                             maxlength="150" autofocus required
                                                                             id="id_username"/></p>
        <p><label for="id_password1" class="sr-only">Password:</label> <input type="password" name="password1"
                                                                              class="form-control"
                                                                              placeholder="Password"
                                                                              required id="id_password1"/></p>
        <p><label for="id_password2" class="sr-only">Password confirmation:</label> <input type="password"
                                                                                           class="form-control"
                                                                                           placeholder="Password Confirmation"
                                                                                           name="password2" required
                                                                                           id="id_password2"/></p>


        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>


    </form>


</div> <!-- /container -->
</body>
</html>